name: CI

on:
  push:
    paths:
      - '.github/workflows/*'
      - 'shell_scripts/*'
      - 'python_scripts/*'
      - 'tests/*'
  pull_request:
    paths:
      - '.github/workflows/*'
      - 'shell_scripts/*'
      - 'python_scripts/*'
      - 'tests/*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']

    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Pull LFS files
        run: |
          git lfs pull
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: List input_data directory
        run: |
          ls tests/../input_data
    
      - name: Run tests with pytest
        run: |
          pytest tests/
