name: CI

on:
  push:
    paths:
      - '.github/workflows/*'
      - 'shell_scripts/*'
      - 'python_scripts/*'
      - 'tests/*'
  pull_request:
    paths:
      - '.github/workflows/*'
      - 'shell_scripts/*'
      - 'python_scripts/*'
      - 'tests/*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']

    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Pull specific LFS files
        run: |
          git lfs pull --include="input_data/LOCUST_SPR-045-14_OutputFiles/*"
          git lfs pull --include="input_data/profiles_SPR-045-16.CDF"
          git lfs pull --include="input_data/SPR-045-16.eqdsk"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
    
      - name: Run tests with pytest
        run: |
          pytest tests/
